### PR TITLE
correcting_measurement_units

### LINKED ISSUE #20: Example Output
In the example output, it says Rad/S, but the output is actually Deg/s

### PR DESCRIPTION
**Pull request by jposada202020**
solves #20 .
The design guide is correct. However the sensor gives DPS or degrees per second as an output measure
This is stated in the Datasheet
image
also in the learning guide
https://learn.adafruit.com/comparing-gyroscope-datasheets

Changes were made in the example and also in the library.

The DPS measure was confirmed changing the `rng` parameter. and tested in 
```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
```

### CODE REVIEW

**Comment by ladyada** [comment]
ehh? the sensor should not be returning dps - it should definitely be rps which is the SI unit we are standardizing on
https://circuitpython.readthedocs.io/en/6.2.x/docs/design_guide.html#sensor-properties-and-units
id rather do a major update, so this sensor is the same as every other gyro
zat ok?

**Comment by jposada202020** [comment]
Will do~, was not sure to the path to be taken, for that reason I changed the example instead of the library. Will change this library to get `rad/s` and verify if other gyros/accel have any issue that need to be corrected.
Thanks

**Comment by ladyada** [comment]
thank you - this was a very early library, we probably hadnt settled on the units by then :)

**Comment by jposada202020** [comment]
This one was left out while correcting the Gyro units..:)

**Review by tannewt — APPROVED** [review]
Thank you!

**Comment by evaherrada** [comment]
@jposada202020 Do you think you could reopen this branch and make another PR? I messed something up with moving to main and this PR wasn't included in the main branch.

**Comment by tannewt** [comment]
Hold off on making another PR. We should be able to recover the full history.

**Comment by jposada202020** [comment]
:) will do

**Pull request merged**
